---
############# Copy Docker image tar files on remote server ###############

- name: Copy Docker image tar files on remote server
  ansible.builtin.copy:
    src: '{{ item.image.archive_path }}'
    dest: '{{ PATH_IMAGES }}/{{ item.image.name }}_latest.tar'
  loop: '{{ services }}'
  loop_control:
    loop_var: item
  when: item.image.archive_path is defined


############### Load Docker images on remote server ################

- name: Load Docker images on remote server
  community.docker.docker_image:
    name: '{{ item.image.name }}:latest'
    source: load
    force_source: yes
    force_tag: yes
    load_path: '{{ PATH_IMAGES }}/{{ item.image.name }}_latest.tar'
  loop: '{{ services }}'
  loop_control:
    loop_var: item
  async: 500
  poll: 0
  when: item.image.archive_path is defined
  register: async_results

- name: Check sync status (Load Docker images on remote server)
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 40
  delay: 10

##############################################################

- name: Remove unused Docker images
  command: docker image prune -f
  async: 300
  poll: 0
