---
- name: Uploading Images
  include_tasks: images.yml
  when: inventory_hostname != 'localhost'

- name: Copy traefik.yml config on remote server
  ansible.builtin.copy:
    src: /files/traefik
    dest: "{{ PATH_DESTINATION }}"
  when: inventory_hostname != 'localhost'

- name: Copy the tar archive to the remote server
  ansible.builtin.copy:
    src: "{{ PATH }}/mock_data_archive.tar"
    dest: "{{ PATH_DESTINATION }}/"
  when: inventory_hostname != 'localhost'

- name: Extract the tar archive on the remote server
  ansible.builtin.unarchive:
    src: "{{ PATH_DESTINATION }}/mock_data_archive.tar"
    dest: "{{ PATH_DESTINATION }}/"
    remote_src: yes
  when: inventory_hostname != 'localhost'

- name: Compose Tasks
  include_tasks: compose.yml


