---
SITE_WEB_REPO: 'git@github.com:quent36987/cybermaniac-site-web.git'

services:
  - name: Store
    repo:
      url: 'git@github.com:quent36987/cybermaniac-store.git'
      dest: /repo/cybermaniac-store
      key_file: /home/quentin/.ssh/id_ed25519
    image:
      name: store-image
      path: /repo/cybermaniac-store
      dockerfile: Dockerfile-ansible
      args:
        GATSBY_TELEMETRY_DISABLED: "1"
        GATSBY_STORE_URL: "https://admin.cybermaniacouioi"
      archive_path: /repo/cybermaniac-store/store-image_latest.tar

  - name: Site Web
    repo:
      url: '{{ SITE_WEB_REPO }}'
      dest: /repo/cybermaniac-site-web
      key_file: /home/quentin/.ssh/id_ed25519
    image:
      name: site-web-image
      path: /repo/cybermaniac-site-web
      dockerfile: Dockerfile-ansible
      args:
        PUBLIC_STORE_URL: "https://boutique.cybermaniacfr"
      archive_path: /repo/cybermaniac-site-web/site-web-image_latest.tar

  - name: Backend
    repo:
      url: 'git@github.com:quent36987/cybermaniac-backend.git'
      dest: /repo/cybermaniac-backend
      key_file: /home/quentin/.ssh/id_ed25519
    image:
      name: cybermaniac-backend-image
      path: /repo/cybermaniac-backend
      dockerfile: Dockerfile-ansible
    archive_path: /repo/cybermaniac-backend/cybermaniac-backend-image_latest.tar
