---
ADMIN_DOMAIN: "admin.{{ DOMAIN }}"
BOUTIQUE_DOMAIN: "boutique.{{ DOMAIN }}"
SITE_WEB_DOMAIN: "{{ DOMAIN }}"
MONITOR_DOMAIN: "monitor.{{ DOMAIN }}"
PGADMIN_DOMAIN: "pgadmin.{{ DOMAIN }}"

ADMIN_URL: "https://{{ ADMIN_DOMAIN }}"
BOUTIQUE_URL: "https://{{ BOUTIQUE_DOMAIN }}"
SITE_WEB_URL: "https://{{ SITE_WEB_DOMAIN }}"
MONITOR_URL: "https://{{ MONITOR_DOMAIN }}"
PGADMIN_URL: "https://{{ PGADMIN_DOMAIN }}"

SITE_WEB_IMAGE: site-web-image
STORE_IMAGE: store-image
BACKEND_IMAGE: backend-image
POSTGRES_IMAGE: postgres-image

PATH: "/cyber"
IMAGES_REPOSITORY: "{{ PATH }}/images"
GIT_REPOSITORY: "{{ PATH }}/repo"
MOCK_DATA_REPOSITORY: "{{ PATH }}/mock_data"

PATH_DESTINATION: "~/ansible"

