services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
