---
- name: Copy and load Docker image tar files on remote server
  ansible.builtin.copy:
    src: '{{ item.image.archive_path }}'
    dest: '~/ansible/{{ item.name }}_latest.tar'
  community.docker.docker_image:
    name: '{{ item.image.name }}:latest'
    source: load
    load_path: '~/ansible/{{ item.name }}_latest.tar'
  loop: '{{ services }}'
  loop_control:
    loop_var: item
  when: item.image_archive_path is defined