---
- name: Install Docker module for Python
  ansible.builtin.pip:
    name: docker
    executable: pip3

- name: Install Docker Compose module for Python
  ansible.builtin.pip:
    name: docker-compose
    executable: pip3

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ PATH_DESTINATION }}"

- name: Uploading Images
  include_tasks: images.yml

- name: Copy traefik.yml config on remote server
  ansible.builtin.copy:
    src: /files/traefik
    dest: "{{ PATH_DESTINATION }}/"

- name: Copy the tar archive to the remote server
  ansible.builtin.copy:
    src: "{{ PATH }}/mock_data_archive.tar"
    dest: "{{ PATH_DESTINATION }}/"

- name: Extract the tar archive on the remote server
  ansible.builtin.unarchive:
    src: "{{ PATH_DESTINATION }}/mock_data_archive.tar"
    dest: "{{ PATH_DESTINATION }}/"
    remote_src: yes


- name: Compose Tasks
  include_tasks: compose.yml

