---
- name: Install Docker module for Python
  ansible.builtin.pip:
    name: docker
    executable: pip3

- name: Install Docker Compose module for Python
  ansible.builtin.pip:
    name: docker-compose
    executable: pip3

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ PATH_DESTINATION }}"

- name: Uploading Images
  include_tasks: images.yml

- name: Copy traefik.yml file on remote server
  ansible.builtin.copy:
    src: /files/traefik
    dest: "{{ PATH_DESTINATION }}/"

- name: Copy images file on remote server
  ansible.builtin.copy:
    src: /tmp/images
    dest: "{{ PATH_DESTINATION }}/"

- name: Compose Tasks
  include_tasks: compose.yml

