  logLevel: INFO

  api:
    insecure: true
    dashboard: true

  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: web-secure
            scheme: https
            permanent: true
    web-secure:
        address: ":443"

  providers:
    file:
      filename: /etc/traefik/tls.yml
    docker:
      endpoint: unix:///var/run/docker.sock
      watch: true
      exposedByDefault: false
      defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"
